### ISSUE TITLE
Crash found

### ISSUE THREAD

**Issue by cerver1** [adpth/Calculator-Application#2]
Each time you click an operator("/,%,x,-,+,=") button without clicking entering a number the app crashes. 
I have a few fixes in mind but I'm not sure what your intentions are for this repo so I didn't implement any changes.

**Comment by adpth** [comment]
In general, people will give the first input a number before they click any operation button, I have not thought in that perspective. Thank you for letting me know that crash issue. I have fixed that
Happy Coding :)
